#!/usr/bin/bash

source "${srcdir}/config.bash"

# Set config as x86-64_v3
setConfig config
setVal CONFIG_X86_64_VERSION 3

# General setups
enable CONFIG_EXPERT
disable CONFIG_USELIB

# AUR package linux-xanmod defaulted
enableAll \
    CONFIG_STACK_VALIDATION \
    CONFIG_IKCONFIG \
    CONFIG_IKCONFIG_PROC

# Disable staging driver
disable CONFIG_STAGING

# Disable support for special cpu
enable CONFIG_PROCESSOR_SELECT
disableAll \
    CONFIG_CPU_SUP_HYGON \
    CONFIG_CPU_SUP_CENTAUR \
    CONFIG_CPU_SUP_ZHAOXIN

# Disable display and sound
disableAll \
    CONFIG_AUXDISPLAY \
    CONFIG_PANEL \
    CONFIG_AGP \
    CONFIG_VGA_SWITCHEROO \
    CONFIG_DRM \
    CONFIG_FB \
    CONFIG_LCD_CLASS_DEVICE \
    CONFIG_BACKLIGHT_CLASS_DEVICE \
    CONFIG_USB_APPLEDISPLAY \
    CONFIG_SAMSUNG_Q10 \
    CONFIG_ACPI_CMPC \
    CONFIG_SOUND \
    CONFIG_MEDIA_SUPPORT

# Disable noneeded filesystems
disableAll \
    CONFIG_TMPFS_QUOTA \
    CONFIG_QUOTA \
    CONFIG_JFS_FS \
    CONFIG_XFS_FS \
    CONFIG_GFS2_FS \
    CONFIG_OCFS2_FS \
    CONFIG_NILFS2_FS \
    CONFIG_F2FS_FS \
    CONFIG_BCACHEFS_FS \
    CONFIG_ZONEFS_FS \
    CONFIG_OVERLAY_FS \
    CONFIG_ISO9660_FS \
    CONFIG_UDF_FS \
    CONFIG_MSDOS_FS \
    CONFIG_EXFAT_FS \
    CONFIG_NTFS_FS \
    CONFIG_NTFS3_FS \
    CONFIG_MISC_FILESYSTEMS \
    CONFIG_NETWORK_FILESYSTEMS \
    CONFIG_EXT4_USE_FOR_EXT2
module CONFIG_FUSE_FS

# Disable noneeded partition types
disableAll \
    CONFIG_AIX_PARTITION \
    CONFIG_OSF_PARTITION \
    CONFIG_AMIGA_PARTITION \
    CONFIG_ATARI_PARTITION \
    CONFIG_MAC_PARTITION \
    CONFIG_BSD_DISKLABEL \
    CONFIG_MINIX_SUBPARTITION \
    CONFIG_SOLARIS_X86_PARTITION \
    CONFIG_UNIXWARE_DISKLABEL \
    CONFIG_LDM_PARTITION \
    CONFIG_SGI_PARTITION \
    CONFIG_ULTRIX_PARTITION \
    CONFIG_SUN_PARTITION \
    CONFIG_KARMA_PARTITION \
    CONFIG_SYSV68_PARTITION \
    CONFIG_CMDLINE_PARTITION

# Disable noneeded drivers
disableAll \
    CONFIG_PCCARD \
    CONFIG_GNSS \
    CONFIG_MTD \
    CONFIG_MD \
    CONFIG_FIREWIRE \
    CONFIG_FIREWIRE_NOSY \
    CONFIG_MACINTOSH_DRIVERS \
    CONFIG_HID_SUPPORT \
    CONFIG_USB_SUPPORT \
    CONFIG_MMC \
    CONFIG_SCSI_UFSHCD \
    CONFIG_MEMSTICK \
    CONFIG_ACCESSIBILITY \
    CONFIG_CHROME_PLATFORMS \
    CONFIG_CZNIC_PLATFORMS \
    CONFIG_MELLANOX_PLATFORM \
    CONFIG_SURFACE_PLATFORMS \
    CONFIG_SOUNDWIRE \
    CONFIG_FPGA \
    CONFIG_I3C \
    CONFIG_ANDROID_BINDER_IPC \
    CONFIG_HAMRADIO \
    CONFIG_SCSI_BNX2_ISCSI \
    CONFIG_SCSI_BNX2X_FCOE \
    CONFIG_SCSI_CXGB3_ISCSI \
    CONFIG_SCSI_CXGB4_ISCSI \
    CONFIG_IIO \
    CONFIG_SSB \
    CONFIG_SIOX \
    CONFIG_SLIMBUS \
    CONFIG_IPACK_BUS

# Disable noneeded network-related modules
disableAll \
    CONFIG_BT \
    CONFIG_IPWIRELESS \
    CONFIG_WWAN \
    CONFIG_WIRELESS \
    CONFIG_RFKILL \
    CONFIG_NET_9P \
    CONFIG_NFC \
    CONFIG_CAN \
    CONFIG_AF_RXRPC \
    CONFIG_CAIF \
    CONFIG_TCP_CONG_BIC \
    CONFIG_TCP_CONG_CUBIC \
    CONFIG_TCP_CONG_WESTWOOD \
    CONFIG_TCP_CONG_HTCP \
    CONFIG_TCP_CONG_HSTCP \
    CONFIG_TCP_CONG_HYBLA \
    CONFIG_TCP_CONG_VEGAS \
    CONFIG_TCP_CONG_NV \
    CONFIG_TCP_CONG_SCALABLE \
    CONFIG_TCP_CONG_LP \
    CONFIG_TCP_CONG_VENO \
    CONFIG_TCP_CONG_YEAH \
    CONFIG_TCP_CONG_ILLINOIS \
    CONFIG_TCP_CONG_DCTCP \
    CONFIG_TCP_CONG_CDG \
    CONFIG_INFINIBAND \
    CONFIG_ARCNET \
    CONFIG_ATM_DRIVERS \
    CONFIG_ETHERNET \
    CONFIG_FDDI \
    CONFIG_MICREL_KS8995MA \
    CONFIG_PSE_CONTROLLER \
    CONFIG_MCTP_SERIAL \
    CONFIG_USB_NET_DRIVERS \
    CONFIG_PLIP \
    CONFIG_PPP \
    CONFIG_SLIP \
    CONFIG_WLAN \
    CONFIG_FUJITSU_ES \
    CONFIG_ISDN

# Disable other noneeded moudles
disableAll \
    CONFIG_INPUT_JOYDEV \
    CONFIG_INPUT_JOYSTICK \
    CONFIG_INPUT_TABLET \
    CONFIG_INPUT_TOUCHSCREEN \
    CONFIG_INPUT_MISC \
    CONFIG_RMI4_CORE \
    CONFIG_HID_RMI \
    CONFIG_SECURITY_SELINUX \
    CONFIG_ACPI_APEI # Need by CONFIG_MISC_FILESYSTEMS

# Disable x86 support
disableAll \
    CONFIG_IA32_EMULATION \
    CONFIG_COMPAT_32BIT_TIME \
    CONFIG_X86_X32_ABI

# Disable virtualization support
disable CONFIG_VIRTUALIZATION

# Disable suspend and hibernation support
disableAll \
    CONFIG_SUSPEND \
    CONFIG_HIBERNATION

# Compress modules with zstd
enableAll \
    CONFIG_MODULE_COMPRESS \
    CONFIG_MODULE_COMPRESS_ZSTD
disable MODULE_COMPRESS_GZIP

# Zswap
enableAll \
    CONFIG_ZSWAP_DEFAULT_ON \
    CONFIG_ZSWAP_COMPRESSOR_DEFAULT_ZSTD \
    CONFIG_ZSWAP_ZPOOL_DEFAULT_ZSMALLOC \
    CONFIG_ZSMALLOC
disableAll \
    CONFIG_ZSWAP_COMPRESSOR_DEFAULT_LZ4 \
    CONFIG_ZSWAP_ZPOOL_DEFAULT_Z3FOLD \
    CONFIG_ZBUD \
    CONFIG_Z3FOLD

# Codepage
enableAll \
    CONFIG_NLS_ISO8859_1 \
    CONFIG_NLS_UTF8 \
    CONFIG_FAT_DEFAULT_UTF8

# Compress modules with zstandard
disable CONFIG_MODULE_COMPRESS_NONE
enable CONFIG_MODULE_COMPRESS_ZSTD

# HZ
enable CONFIG_HZ_1000
disable CONFIG_HZ_250

# Builtin btrfs
enable CONFIG_BTRFS_FS

# Enable LTO
disable CONFIG_LTO_NONE
enable CONFIG_LTO_CLANG_THIN

# Fix issue from systemd
# systemd[1]: Failed to find module 'autofs4'
enable CONFIG_AUTOFS_FS

# Fix warning from device-mapper
# kernel: device-mapper: core: CONFIG_IMA_DISABLE_HTABLE is disabled.
#     Duplicate IMA measurements will not be recorded in the IMA log.
enable CONFIG_IMA_DISABLE_HTABLE

# Elaina kernel
setStr CONFIG_DEFAULT_HOSTNAME elaina
